---
title: "Thesis"
author: "Rachel Good"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

options(digits = 3)
```

```{r packages}
library(dplyr)
library(ggplot2)
```

```{r new_data} 
# Set working directory
# setwd()


new_data <- read.table('data/Military-Subsample_Alcohol/Military-Subsample_Alcohol.dat', sep=' ')
names(new_data) <- c('R0000100',
  'R0029800',
  'R0030400',
  'R0030500',
  'R0031100',
  'R0034300',
  'R0036100',
  'R0038400',
  'R0040500',
  'R0173600',
  'R0214700',
  'R0214800',
  'R0236500',
  'R0241900',
  'R0242700',
  'R0247500',
  'R0248400',
  'R0253300',
  'R0260300',
  'R0424700',
  'R0430000',
  'R0430800',
  'R0435600',
  'R0436500',
  'R0441400',
  'R0443300',
  'R0671400',
  'R0672000',
  'R0677700',
  'R0678500',
  'R0685600',
  'R0686500',
  'R0691500',
  'R0691900',
  'R0692300',
  'R0693400',
  'R0780200',
  'R0780400',
  'R0781100',
  'R0913200',
  'R0913800',
  'R0919400',
  'R0920200',
  'R0927400',
  'R0928500',
  'R0933700',
  'R0934100',
  'R0934500',
  'R0936400',
  'R1021700',
  'R1022000',
  'R1022100',
  'R1023600',
  'R1221900',
  'R1222500',
  'R1228900',
  'R1230000',
  'R1238200',
  'R1243500',
  'R1243900',
  'R1244300',
  'R1246700',
  'R1391200',
  'R1391300',
  'R1391400',
  'R1392900',
  'R1393400',
  'R1393500',
  'R1393600',
  'R1393700')


# Handle missing values

  new_data[new_data == -1] = NA  # Refused 
  new_data[new_data == -2] = NA  # Dont know 
  new_data[new_data == -3] = NA  # Invalid missing 
  new_data[new_data == -4] = NA  # Valid missing 
  new_data[new_data == -5] = NA  # Non-interview 
```

```{r categorize_values}
# If there are values not categorized they will be represented as NA

vallabels = function(data) {
  data$R0029800 <- factor(data$R0029800, 
    levels=c(1.0,2.0,3.0), 
    labels=c("SERVED IN 1 BRANCH",
      "SERVED IN ACTIVE & RESERVE",
      "DELAYED SERVICE"))
  data$R0030400 <- factor(data$R0030400, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0030500 <- factor(data$R0030500, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0031100 <- factor(data$R0031100, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0034300 <- factor(data$R0034300, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0036100 <- factor(data$R0036100, 
    levels=c(1.0,2.0,3.0), 
    labels=c("SERVING IN ACTIVE FORCES",
      "SERVING IN RESERVE/GUARD",
      "NOT SERVING AT ALL"))
  data$R0038400 <- factor(data$R0038400, 
    levels=c(1.0,2.0,3.0), 
    labels=c("ACTIVE STATUS",
      "RESERVE STATUS",
      "NOT SERVING"))
  data$R0040500 <- factor(data$R0040500, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0173600 <- factor(data$R0173600, 
    levels=c(1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0), 
    labels=c("CROSS MALE WHITE",
      "CROSS MALE WH POOR",
      "CROSS MALE BLACK",
      "CROSS MALE HISPANIC",
      "CROSS FEMALE WHITE",
      "CROSS FEMALE WH POOR",
      "CROSS FEMALE BLACK",
      "CROSS FEMALE HISPANIC",
      "SUP MALE WH POOR",
      "SUP MALE BLACK",
      "SUP MALE HISPANIC",
      "SUP FEM WH POOR",
      "SUP FEMALE BLACK",
      "SUP FEMALE HISPANIC",
      "MIL MALE WHITE",
      "MIL MALE BLACK",
      "MIL MALE HISPANIC",
      "MIL FEMALE WHITE",
      "MIL FEMALE BLACK",
      "MIL FEMALE HISPANIC"))
  data$R0214700 <- factor(data$R0214700, 
    levels=c(1.0,2.0,3.0), 
    labels=c("HISPANIC",
      "BLACK",
      "NON-BLACK, NON-HISPANIC"))
  data$R0214800 <- factor(data$R0214800, 
    levels=c(1.0,2.0), 
    labels=c("MALE",
      "FEMALE"))
  data$R0236500 <- factor(data$R0236500, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0241900 <- factor(data$R0241900, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0242700 <- factor(data$R0242700, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0247500 <- factor(data$R0247500, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0248400 <- factor(data$R0248400, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0253300 <- factor(data$R0253300, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0260300 <- factor(data$R0260300, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0424700 <- factor(data$R0424700, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0430000 <- factor(data$R0430000, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0430800 <- factor(data$R0430800, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0435600 <- factor(data$R0435600, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0436500 <- factor(data$R0436500, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0441400 <- factor(data$R0441400, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0443300 <- factor(data$R0443300, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0671400 <- factor(data$R0671400, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0672000 <- factor(data$R0672000, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0677700 <- factor(data$R0677700, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0678500 <- factor(data$R0678500, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0685600 <- factor(data$R0685600, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0686500 <- factor(data$R0686500, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0691500 <- factor(data$R0691500, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0691900 <- factor(data$R0691900, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0692300 <- factor(data$R0692300, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0693400 <- factor(data$R0693400, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
#  data$R0780200[0.0 <= data$R0780200 & data$R0780200 <= 10.0] <- 0.0
#  data$R0780200[27.0 <= data$R0780200 & data$R0780200 <= 99999.0] <- 27.0
#  data$R0780200 <- factor(data$R0780200, 
#    levels=c(0.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0), 
#    labels=c("0 TO 10: < 11",
#      "11",
#      "12",
#      "13",
#      "14",
#      "15",
#      "16",
#      "17",
#      "18",
#      "19",
#      "20",
#      "21",
#      "22",
#      "23",
#      "24",
#      "25",
#      "26",
#      "27 TO 99999: 27+"))
  data$R0780400 <- factor(data$R0780400, 
    levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0), 
    labels=c("NEVER",
      "ONCE",
      "2 OR 3 TIMES",
      "4 OR 5 TIMES",
      "6 OR 7 TIMES",
      "8 OR 9 TIMES",
      "10 OR MORE TIMES"))
  data$R0781100 <- factor(data$R0781100, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0913200 <- factor(data$R0913200, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0913800 <- factor(data$R0913800, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0919400 <- factor(data$R0919400, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0920200 <- factor(data$R0920200, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0927400 <- factor(data$R0927400, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0928500 <- factor(data$R0928500, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0933700 <- factor(data$R0933700, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0934100 <- factor(data$R0934100, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0934500 <- factor(data$R0934500, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R0936400 <- factor(data$R0936400, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
#  data$R1021700[0.0 <= data$R1021700 & data$R1021700 <= 9.0] <- 0.0
# data$R1021700[26.0 <= data$R1021700 & data$R1021700 <= 99999.0] <- 26.0
#  data$R1021700 <- factor(data$R1021700, 
#    levels=c(0.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0,25.0,26.0), 
#    labels=c("0 TO 9: < 10",
#      "10",
#      "11",
#      "12",
#      "13",
#      "14",
#      "15",
#      "16",
#      "17",
#      "18",
#      "19",
#      "20",
#      "21",
#      "22",
#      "23",
#      "24",
#      "25",
#      "26 TO 99999: 26+"))
  data$R1022000 <- factor(data$R1022000, 
    levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0), 
    labels=c("NEVER",
      "ONCE",
      "2 OR 3 TIMES",
      "4 OR 5 TIMES",
      "6 OR 7 TIMES",
      "8 OR 9 TIMES",
      "10 OR MORE TIMES"))
#  data$R1022100[16.0 <= data$R1022100 & data$R1022100 <= 99999.0] <- 16.0
#  data$R1022100 <- factor(data$R1022100, 
#    levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0), 
#    labels=c("0",
#      "1",
#      "2",
#      "3",
#      "4",
#      "5",
#      "6",
#      "7",
#      "8",
#      "9",
#      "10",
#      "11",
#      "12",
#      "13",
#      "14",
#      "15",
#      "16 TO 99999: 16+"))
  data$R1023600 <- factor(data$R1023600, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R1221900 <- factor(data$R1221900, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R1222500 <- factor(data$R1222500, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R1228900 <- factor(data$R1228900, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R1230000 <- factor(data$R1230000, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R1238200 <- factor(data$R1238200, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R1243500 <- factor(data$R1243500, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R1243900 <- factor(data$R1243900, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R1244300 <- factor(data$R1244300, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R1246700 <- factor(data$R1246700, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R1391200 <- factor(data$R1391200, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R1391300 <- factor(data$R1391300, 
    levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0), 
    labels=c("NEVER",
      "ONCE",
      "2 OR 3 TIMES",
      "4 OR 5 TIMES",
      "6 OR 7 TIMES",
      "8 OR 9 TIMES",
      "10 OR MORE TIMES"))
#  data$R1391400[16.0 <= data$R1391400 & data$R1391400 <= 99999.0] <- 16.0
#  data$R1391400 <- factor(data$R1391400, 
#    levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0), 
#    labels=c("0",
#      "1",
#      "2",
#      "3",
#      "4",
#      "5",
#      "6",
#      "7",
#      "8",
#      "9",
#      "10",
#      "11",
#      "12",
#      "13",
#      "14",
#      "15",
#      "16 TO 99999: 16+"))
  data$R1392900 <- factor(data$R1392900, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R1393400 <- factor(data$R1393400, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R1393500 <- factor(data$R1393500, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R1393600 <- factor(data$R1393600, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  data$R1393700 <- factor(data$R1393700, 
    levels=c(0.0,1.0), 
    labels=c("NO",
      "YES"))
  return(data)
}
```

```{r variable_labels}
varlabels <- c("ID# (1-12686) 79",
  "ICHK SERVED BOTH ACTIVE AF AND GARD 79",
  "ICHK IN AAF M-RCNT ENLSTMNT 79",
  "ICHK IN AAF 2ND M-RCNT ENLSTMNT 79",
  "IN AAF M-RCNT PRD OF SRVC 79",
  "ICHK R CURRENTLY ON AAF DUTY 79",
  "ICHK R CURRENTLY ON AAF DUTY 79",
  "ICHK R CURRENTLY ON AAF DUTY 79",
  "ICHK CURRENTLY AAF RESERVES/GARD 79",
  "SAMPLE ID  79 INT",
  "RACL/ETHNIC COHORT /SCRNR 79",
  "SEX OF R 79",
  "ICHK R IN AAF @ LINT 80",
  "ICHK R ENTER AAF M-RCNT ENLSTMNT 80",
  "ICHK R CURRENTLY IN AAF 80",
  "ICHK R IN AAF @ LINT 80",
  "ICHK R CURRENTLY IN AAF 80",
  "TIME SERVE ACT AF (NOT CUR ENLSTD) 80",
  "ICHK R CURRENTLY ON AAF DUTY 80",
  "ICHK R IN AAF @ LINT 81",
  "ICHK R ENTER AAF M-RCNT ENLSTMNT 81",
  "ICHK R CURRENTLY IN AAF 81",
  "ICHK R IN AAF @ LINT 81",
  "ICHK R CURRENTLY IN AAF 81",
  "TIME SERVE ACT AF (NOT CUR ENLSTD) 81",
  "ICHK R CURRENTLY ON AAF DUTY 81",
  "ICHK IN AAF @ LINT SAME BRANCH 82",
  "ICHK R IN AAF @ LINT 82",
  "ICHK R ENTER AAF M-RCNT ENLSTMNT 82",
  "ICHK R CURRENTLY IN AAF 82",
  "ICHK R IN AAF @ LINT 82",
  "ICHK R CURRENTLY IN AAF 82",
  "TIME SERVE ACT AF (NOT CUR ENLSTD) 82",
  "ICHK DID ENTER AAF NOT NOW ENLSTD 82",
  "ICHK R IN THE AAF (NOT NOW ENLSTD) 82",
  "ICHK R CURRENTLY ON AAF DUTY 82",
  "ALCHL-AGE START DRNK 82",
  "ALCHL-FREQ 6/> DRNK @ 1 TM LAST MO 82",
  "ALCHL-DRNK INTERFERE W/JOB 82",
  "ICHK R ACT ARM FORCE LINT SAME 83",
  "ICHK R IN AAF @ LINT 83",
  "ICHK R ENTER AAF M-RCNT ENLSTMNT 83",
  "ICHK R CURRENTLY IN AAF 83",
  "ICHK R IN AAF @ LINT 83",
  "ICHK R CURRENTLY IN AAF 83",
  "TIME SERVE ACT AF (NOT CUR ENLSTD) 83",
  "ICHK DID ENTER AAF NOT NOW ENLSTD 83",
  "ICHK R IN THE AAF (NOT NOW ENLSTD) 83",
  "ICHK R CURRENTLY ON AAF DUTY 83",
  "ALCHL-AGE START DRNK 83",
  "ALCHL-FREQ 6/> DRNK @ 1 TM LAST MO 83",
  "ALCHL-#DAYS DRANK ALCOHOL LAST MO 83",
  "ALCHL-DRNK INTERFERE W/JOB 83",
  "ICHK IN AAF @ LINT SAME BR AS @ LINT 84",
  "ICHK R IN AAF @ LINT 84",
  "ICHK R ENTER AAF M-RCNT ENLSTMNT 84",
  "ICHK R CURRENTLY IN AAF 84",
  "ICHK R CURRENTLY IN AAF 84",
  "TIME SERVE ACT AF (NOT CUR ENLSTD) 84",
  "ICHK DID ENTER AAF NOT NOW ENLSTD 84",
  "ICHK R IN THE AAF (NOT NOW ENLSTD) 84",
  "ICHK R CURRENTLY ON AAF DUTY 84",
  "ALCHL-DRNK INTERFERE W/JOB 84",
  "ALCHL-FREQ 6/> DRNK @ 1 TM LAST MO 84",
  "ALCHL-#DAYS DRANK ALCOHOL LAST MO 84",
  "ALCHL-DRNK INTERFERE W/JOB 84",
  "ALCHL-AFRAID BE/BECOME ALCHLC 84",
  "ALCHL-DIFF STOP DRNK UNTIL INTOX 84",
  "ALCHL-DONT REMEMBER THING WHILE DRNK 84",
  "ALCHL-TAKE DRNK 1ST THING MORN 84"
)
```

```{r useful_names}
# Use qnames rather than rnums
#Change these names to be useful
#AD = ACTIVE DUTY
#ARNG= ACTIVE RESERVE NATIONAL GUARD
#INT = INTERVIEW
#DLI = DATE LAST INT
qnames = function(data) {
  names(data) <- c("CASEID",
    "AD_AND_ARNG_79",#MIL-8
    "AD_RECENT_ENLIST_79", #Q4-11
    "AD_2NDRECENT_ENLIST_79",#Q4-12A
    "AD_RECENT_SERVICEPERIOD_79",#MIL-13A
    "CURRENT_AD_YN_79",#MIL-27
    "CURRENT_AD_ARNG_79",#MIL-36 
    "CURRENT_AD_ARNG_STATUS_79",#MIL-48
    "CURRENT_AD_ARNG_YN_79",#MIL-59
    "SAMPLE_ID_79",
    "RACE",
    "SAMPLE_SEX_79",
    "AD_DLI_NOTSAME_BRANCH_80",#MIL-15
    "NEW_ENLIST_AD_80",#Q4-11
    "AD_DLI_SAME_BRANCH_80_Q1",#Q4-15 #G1_CONFUSION_Q4-15 #DUP
    "AD_DLI_SAME_BRANCH_80_Q2",#MIL-13
    "AD_DLI_SAME_BRANCH_80_Q3",#MIL-59 #G1_CONFUSION_MIL-59
    "TIME_SERVED_YN_80",#Q4-12
    "CURRENT_AD_YN_80",#MIL-48 #G1_CONFUSION_MIL-48 #DUP
    "AD_DLI_NOTSAME_BRANCH_81",#MIL-15
    "NEW_ENLIST_AD_81",#Q4-11 
    "AD_DLI_SAME_BRANCH_81_Q1",#Q4-15 #G1_CONFUSION_Q4-15
    "AD_DLI_SAME_BRANCH_81_Q2",#MIL-13
    "AD_DLI_SAME_BRANCH_81_Q3",#MIL-59 #G1_CONFUSION_MIL-59
    "TIME_SERVED_YN_81",#Q4-12
    "CURRENT_AD_YN_81", #G1_CONFUSION_MIL-48 #DUP
    "AD_DLI_SAME_BRANCH_82_Q4",#Q4-4A 
    "AD_DLI_NOTSAME_BRANCH_82",#MIL-15
    "NEW_ENLIST_AD_82",#Q4-11
    "AD_DLI_SAME_BRANCH_82_Q1",#Q4-15 #G1_CONFUSION_Q4-15 #DUP
    "AD_DLI_SAME_BRANCH_82_Q2",#MIL-13 #DUP
    "AD_DLI_SAME_BRANCH_82_Q3",#MIL-59 #G1_CONFUSION_MIL-59
    "TIME_SERVED_YN_82",#Q4-12
    "NEW_ENLIST_NOTSERVING_82_Q1",#MIL-100 #G2_CONFUSION_MIL-100
    "NEW_ENLIST_NOTSERVING_82_Q2",#Q4-12A #G2_CONFUSION_Q4-12A
    "CURRENT_AD_YN_82",#MIL-48 #G1_CONFUSION_MIL-48 #DUP
    "AGE_START_DRINK_82",#ALCH-2
    "ALC_FREQ6DRINKS_82",#Q12-4
    "ALC_IMPACT_JOB_82",#ALCH-11
    "AD_DLI_SAME_BRANCH_83_Q4", #Q4-4A
    "AD_DLI_NOTSAME_BRANCH_83",#MIL-15
    "NEW_ENLIST_AD_83",#Q4-11
    "AD_DLI_SAME_BRANCH_83_Q1",#Q4-15 #G1_CONFUSION_Q4-15 #DUP
    "AD_DLI_SAME_BRANCH_83_Q2",#MIL-13 #DUP
    "AD_DLI_SAME_BRANCH_83_Q3",#MIL-59 #G1_CONFUSION_MIL-59
    "TIME_SERVED_YN_83",#Q4-12
    "NEW_ENLIST_NOTSERVING_83_Q1",#MIL-100 #G2_CONFUSION_MIL-100 #DUP
    "NEW_ENLIST_NOTSERVING_83_Q2",# Q4-12A #G2_CONFUSION_Q4-12A,
    "CURRENT_AD_YN_83",#MIL-48 #G1_CONFUSION_MIL-48,#DUP
    "AGE_START_DRINK_83",#ALCH-2
    "ALC_FREQ6DRINK_83",#Q12-4
    "NUM_DAY_DRANK_LAST_MONTH_83",#Q12-5
    "ALC_IMPACT_JOB_83",#ALCH-11
    "AD_DLI_SAME_BRANCH_84_Q4",#Q4-4A
    "AD_DLI_NOTSAME_BRANCH_84",#MIL-15
    "NEW_ENLIST_AD_84",#Q4-11
    "AD_DLI_SAME_BRANCH_84_Q1",#Q4-14 #G1_CONFUSION_Q4-15" #DUP
    "AD_DLI_SAME_BRANCH_84_Q3",#MIL-59 #G1_CONFUSION_MIL-59
    "TIME_SERVED_YN_84",#Q4-12
    "NEW_ENLIST_NOTSERVING_84_Q1",#MIL-100 #G2_CONFUSION_MIL-100 #DUP
    "NEW_ENLIST_NOTSERVING_84_Q2",#Q4-12A #G2_CONFUSION_Q4-12A,
    "CURRENT_AD_YN_84",#MIL-48 #G1_CONFUSION_MIL-48, #DUP
    "ALC_IMPACT_JOB_NOALC_LAST30_84",#ALCH-17
    "ALC_FREQ6DRINK_84",#Q12-4
    "NUM_DAY_DRANK_LAST_MONTH_84",#Q12-5
    "ALC_IMPACT_JOB_YESALC_LAST30_84",#ALCH-11
    "AFRAID_ALCOHOLIC_84",#ALCH-18E
    "DRINK_UNTIL_DRUNK_84",#ALCH-18F
    "FORGETS_NEXT_DAY_84",#ALCH-18G
    "DRINK_FIRST_MORNING_84") #ALCH-18H
  return(data)
}
```

```{r name_me_more_stuff}
#********************************************************************************************************

# Remove the '#' before the following line to create a data file called "categories" with value labels. 
#categories <- vallabels(new_data)

# Remove the '#' before the following lines to rename variables using Qnames instead of Reference Numbers
#new_data <- qnames(new_data)

df_data <- qnames(vallabels(new_data))

# Produce summaries for the raw (uncategorized) data file
summary(df_data)

# Remove the '#' before the following lines to produce summaries for the "categories" data file.
#categories <- vallabels(new_data)
#summary(categories)

#************************************************************************************************************

```

```{r noninterview_var}
# Set working directory
# setwd()


new_data <- read.table('data/noninterview_var/noninterview_var.dat', sep=' ')
names(new_data) <- c('R0000100',
  'T8218500')


# Handle missing values

  new_data[new_data == -1] = NA  # Refused 
  new_data[new_data == -2] = NA  # Dont know 
  new_data[new_data == -3] = NA  # Invalid missing 
  new_data[new_data == -4] = NA  # Valid missing 
  new_data[new_data == -5] = NA  # Non-interview 


# If there are values not categorized they will be represented as NA

vallabels = function(data) {
  data$T8218500 <- factor(data$T8218500, 
    levels=c(60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0,69.0,70.0,71.0,72.0,73.0,74.0,75.0,76.0,77.0), 
    labels=c("60: 60  PARENT REFUSAL/BREAKOFF",
      "61: 61  YOUTH REFUSAL/BREAKOFF",
      "62: 62  PARENT & YOUTH REFUSAL/BREAKOFF",
      "63: 63  UNABLE TO LOCATE FAMILY UNIT & YOUTH",
      "64: 64  UNABLE TO LOCATE YOUTH",
      "65: 65  DECEASED",
      "66: 66  OTHER",
      "67: 67  DO NOT REFIELD (VERY DIFFICULT CASE)",
      "68: 68  MILITARY SAMPLE DROPPED",
      "69: 69  SUPPLEMENTAL MALE POOR WHITE SAMPLE DROPPED",
      "70: 70  SUPPLEMENTAL FEMALE POOR WHITE SAMPLE DROPPED",
      "71: 71  YOUTH REFUSAL - VERY DIFFICULT CASE",
      "72: 72  NOT FIELDED IN CURRENT SURVEY YEAR - VERY DIFFICULT CASE",
      "73: 73  NOT INTERVIEWED - INCARCERATED",
      "74: 74  NOT INTERVIEWED - IN MILITARY",
      "75: 75  DECEASED - MEMBER OF DROPPED SPECIAL SAMPLE",
      "76: 76  UNAVAILABLE DURING FIELD PERIOD",
      "77: 77  REFUSAL - BY AVOIDANCE"))
  return(data)
}

varlabels <- c("ID# (1-12686) 79",
  "REASONS FOR NON-INT 2018"
)


# Use qnames rather than rnums

qnames = function(data) {
  names(data) <- c("CASEID_1979",
    "RNI_2018")
  return(data)
}


#********************************************************************************************************

# Remove the '#' before the following line to create a data file called "categories" with value labels. 
#categories <- vallabels(new_data)

# Remove the '#' before the following lines to rename variables using Qnames instead of Reference Numbers
#new_data <- qnames(new_data)
#categories <- qnames(categories)

df_data_rni <- qnames(vallabels(new_data))

# Produce summaries for the raw (uncategorized) data file
summary(df_data_rni)

df_data$REASON_NONINT <- df_data_rni$RNI_2018
summary(df_data)

# Remove the '#' before the following lines to produce summaries for the "categories" data file.
#categories <- vallabels(new_data)
#summary(categories)

#************************************************************************************************************
```

```{r merge_dfs}
df_data$RNI_2018 <-df_data_rni$RNI_2018

```

```{r military_dropped_filter}
df_rni_groupings <- df_data %>% 
  mutate(mil_groups = case_when(RNI_2018 == "68: 68  MILITARY SAMPLE DROPPED" ~ "MIL_DROP",
                                SAMPLE_ID_79 == "MIL MALE WHITE" ~ "OG_MIL",
                                SAMPLE_ID_79 == "MIL MALE BLACK" ~ "OG_MIL",
                                SAMPLE_ID_79 == "MIL MALE HISPANIC" ~ "OG_MIL",
                                SAMPLE_ID_79 == "MIL FEMALE WHITE"~ "OG_MIL",
                                SAMPLE_ID_79 == "MIL FEMALE BLACK"~ "OG_MIL",
                                SAMPLE_ID_79 == "MIL FEMALE HISPANIC"~ "OG_MIL",
                                SAMPLE_ID_79 == "CROSS MALE WHITE" ~ "NON_MIL",
                                SAMPLE_ID_79 == "CROSS MALE WH POOR" ~ "NON_MIL",
                                SAMPLE_ID_79 == "CROSS MALE BLACK" ~ "NON_MIL",
                                SAMPLE_ID_79 == "CROSS MALE HISPANIC" ~ "NON_MIL",
                                SAMPLE_ID_79 == "CROSS FEMALE WHITE" ~ "NON_MIL",
                                SAMPLE_ID_79 == "CROSS FEMALE WH POOR" ~ "NON_MIL",
                                SAMPLE_ID_79 == "CROSS FEMALE BLACK" ~ "NON_MIL",
                                SAMPLE_ID_79 == "CROSS FEMALE HISPANIC" ~ "NON_MIL",
                                SAMPLE_ID_79 == "SUP MALE WH POOR" ~ "NON_MIL",
                                SAMPLE_ID_79 == "SUP MALE BLACK" ~ "NON_MIL",
                                SAMPLE_ID_79 == "SUP MALE HISPANIC" ~ "NON_MIL",
                                SAMPLE_ID_79 == "SUP FEMALE WH POOR" ~ "NON_MIL",
                                SAMPLE_ID_79 == "SUP FEMALE BLACK" ~ "NON_MIL",
                                SAMPLE_ID_79 == "SUP FEMALE HISPANIC" ~ "NON_MIL"))

```


```{r mil_group_visualization}
ggplot(data = df_rni_groupings,
       mapping = aes(x = mil_groups))+
  geom_bar()

```

# Combining BGA Data

```{r}

new_data <- read.table('data/bgadep/good.dat', sep=' ')
names(new_data) <- c('R0000100',
  'R0000500',
  'R0173600',
  'R0214700',
  'R0214800',
  'R1021800',
  'R1022000',
  'R1022100',
  'R3896810',
  'T3044200',
  'T3044300',
  'T5616100',
  'T5616200')


# Handle missing values

  new_data[new_data == -1] = NA  # Refused 
  new_data[new_data == -2] = NA  # Dont know 
  new_data[new_data == -3] = NA  # Invalid missing 
  new_data[new_data == -4] = NA  # Valid missing 
  new_data[new_data == -5] = NA  # Non-interview 


# If there are values not categorized they will be represented as NA

vallabels = function(data) {

  data$R0173600 <- factor(data$R0173600, 
    levels=c(1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0), 
    labels=c("CROSS MALE WHITE",
      "CROSS MALE WH. POOR",
      "CROSS MALE BLACK",
      "CROSS MALE HISPANIC",
      "CROSS FEMALE WHITE",
      "CROSS FEMALE WH POOR",
      "CROSS FEMALE BLACK",
      "CROSS FEMALE HISPANIC",
      "SUP MALE WH POOR",
      "SUP MALE BLACK",
      "SUP MALE HISPANIC",
      "SUP FEM WH POOR",
      "SUP FEMALE BLACK",
      "SUP FEMALE HISPANIC",
      "MIL MALE WHITE",
      "MIL MALE BLACK",
      "MIL MALE HISPANIC",
      "MIL FEMALE WHITE",
      "MIL FEMALE BLACK",
      "MIL FEMALE HISPANIC"))
  data$R0214700 <- factor(data$R0214700, 
    levels=c(1.0,2.0,3.0), 
    labels=c("HISPANIC",
      "BLACK",
      "NON-BLACK, NON-HISPANIC"))
  data$R0214800 <- factor(data$R0214800, 
    levels=c(1.0,2.0), 
    labels=c("MALE",
      "FEMALE"))
  data$R1021800[0.0 <= data$R1021800 & data$R1021800 <= 9.0] <- 0.0
  data$R1021800[26.0 <= data$R1021800 & data$R1021800 <= 99999.0] <- 26.0
  data$R1021800 <- factor(data$R1021800, 
    levels=c(0.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0,25.0,26.0), 
    labels=c("0 TO 9: < 10",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
      "21",
      "22",
      "23",
      "24",
      "25",
      "26 TO 99999: 26+"))
  data$R1022000 <- factor(data$R1022000, 
    levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0), 
    labels=c("NEVER",
      "ONCE",
      "2 OR 3 TIMES",
      "4 OR 5 TIMES",
      "6 OR 7 TIMES",
      "8 OR 9 TIMES",
      "10 OR MORE TIMES"))
  data$R1022100[16.0 <= data$R1022100 & data$R1022100 <= 99999.0] <- 16.0
  data$R1022100 <- factor(data$R1022100, 
    levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0), 
    labels=c("0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16 TO 99999: 16+"))
  data$R3896810[1.0 <= data$R3896810 & data$R3896810 <= 9.0] <- 1.0
  data$R3896810[10.0 <= data$R3896810 & data$R3896810 <= 19.0] <- 10.0
  data$R3896810[20.0 <= data$R3896810 & data$R3896810 <= 29.0] <- 20.0
  data$R3896810[30.0 <= data$R3896810 & data$R3896810 <= 39.0] <- 30.0
  data$R3896810[40.0 <= data$R3896810 & data$R3896810 <= 49.0] <- 40.0
  data$R3896810[50.0 <= data$R3896810 & data$R3896810 <= 59.0] <- 50.0
  data$R3896810[60.0 <= data$R3896810 & data$R3896810 <= 69.0] <- 60.0
  data$R3896810 <- factor(data$R3896810, 
    levels=c(0.0,1.0,10.0,20.0,30.0,40.0,50.0,60.0), 
    labels=c("0",
      "1 TO 9",
      "10 TO 19",
      "20 TO 29",
      "30 TO 39",
      "40 TO 49",
      "50 TO 59",
      "60 TO 69"))
  data$T3044200[10.0 <= data$T3044200 & data$T3044200 <= 999.0] <- 10.0
  data$T3044200 <- factor(data$T3044200, 
    levels=c(0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0), 
    labels=c("0",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10 TO 999: 10+"))
  data$T3044300 <- factor(data$T3044300, 
    levels=c(0.0,1.0,2.0,3.0,4.0,5.0), 
    labels=c("Never in the last 30 days",
      "Less often than once a week",
      "1 or 2 times per week",
      "3 or 4 times per week",
      "5 or 6 times per week",
      "Everyday"))
  # data$T5616100 <- factor(data$T5616100, 
  #   levels=c(0.0,1.0), 
  #   labels=c("No",
  #     "Yes"))
  # data$T5616200 <- factor(data$T5616200, 
  #   levels=c(0.0,1.0), 
  #   labels=c("No",
  #     "Yes"))
  return(data)
}

varlabels <- c("ID# (1-12686) 79",
  "DATE OF BIRTH - YR 79",
  "SAMPLE ID  79 INT",
  "RACL/ETHNIC COHORT /SCRNR 79",
  "SEX OF R 79",
  "ALCHL-AGE START DRNK 1 TIME WK 83",
  "ALCHL-FREQ 6/> DRNK @ 1 TM LAST MO 83",
  "ALCHL-#DAYS DRANK ALCOHOL LAST MO 83",
  "20-ITEM CES-D SCORE 92",
  "# OF DRINKS R HAS ON AVERAGE DAY 2010",
  "FREQ OF 6 OR MORE DRINKS AT ONCE IN LAST 30 DAYS 2010",
  "LIVE W ONE DEPRESSED MENTALLY ILL SUICIDAL <18 2016",
  "LIVE W PROBLEM DRINKER OR ALCHOLIC <18 2016"
)


# Use qnames rather than rnums

qnames = function(data) {
  names(data) <- c("MCASEID",
    "YoB",
    "SAMPLEID",
    "RACE",
    "SEX",
    "DRINKSTART_1983",
    "DRINKFREQ6_1983",
    "DRINKFREQ_1983",
    "CESD_1992",
    "DRINKAVERAGE_2010",
    "DRINKFREQ6_2010",
    "HOMEDEP_2016",
    "HOMEDRINKER_2016")
  return(data)
}


#********************************************************************************************************

# sneakiness to work with factors

df_data_good <- qnames(new_data)

df_data_goodx <- qnames(vallabels(new_data))

df_data_good[c("MCASEID","YoB","SAMPLEID","RACE","SEX") ]<-df_data_goodx[c("MCASEID","YoB","SAMPLEID","RACE","SEX") ]

rm(df_data_goodx)

# live with


new_data <- read.table('data/bgadep/livewith.dat', sep=' ')
names(new_data) <- c('R0000100',
  'R0173600',
  'R0214700',
  'R0214800',
  'T3974100',
  'T3974200',
  'T4912400',
  'T4912500',
  'T5616100',
  'T5616200')


# Handle missing values

  new_data[new_data == -1] = NA  # Refused 
  new_data[new_data == -2] = NA  # Dont know 
  new_data[new_data == -3] = NA  # Invalid missing 
  new_data[new_data == -4] = NA  # Valid missing 
  new_data[new_data == -5] = NA  # Non-interview 


# If there are values not categorized they will be represented as NA

vallabels = function(data) {
  data$R0173600 <- factor(data$R0173600, 
    levels=c(1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0), 
    labels=c("CROSS MALE WHITE",
      "CROSS MALE WH. POOR",
      "CROSS MALE BLACK",
      "CROSS MALE HISPANIC",
      "CROSS FEMALE WHITE",
      "CROSS FEMALE WH POOR",
      "CROSS FEMALE BLACK",
      "CROSS FEMALE HISPANIC",
      "SUP MALE WH POOR",
      "SUP MALE BLACK",
      "SUP MALE HISPANIC",
      "SUP FEM WH POOR",
      "SUP FEMALE BLACK",
      "SUP FEMALE HISPANIC",
      "MIL MALE WHITE",
      "MIL MALE BLACK",
      "MIL MALE HISPANIC",
      "MIL FEMALE WHITE",
      "MIL FEMALE BLACK",
      "MIL FEMALE HISPANIC"))
  data$R0214700 <- factor(data$R0214700, 
    levels=c(1.0,2.0,3.0), 
    labels=c("HISPANIC",
      "BLACK",
      "NON-BLACK, NON-HISPANIC"))
  data$R0214800 <- factor(data$R0214800, 
    levels=c(1.0,2.0), 
    labels=c("MALE",
      "FEMALE"))
  # data$T3974100 <- factor(data$T3974100, 
  #   levels=c(0.0,1.0), 
  #   labels=c("No",
  #     "Yes"))
  # data$T3974200 <- factor(data$T3974200, 
  #   levels=c(0.0,1.0), 
  #   labels=c("No",
  #     "Yes"))
  # data$T4912400 <- factor(data$T4912400, 
  #   levels=c(0.0,1.0), 
  #   labels=c("No",
  #     "Yes"))
  # data$T4912500 <- factor(data$T4912500, 
  #   levels=c(0.0,1.0), 
  #   labels=c("No",
  #     "Yes"))
  # data$T5616100 <- factor(data$T5616100, 
  #   levels=c(0.0,1.0), 
  #   labels=c("No",
  #     "Yes"))
  # data$T5616200 <- factor(data$T5616200, 
  #   levels=c(0.0,1.0), 
  #   labels=c("No",
  #     "Yes"))
  return(data)
}

varlabels <- c("ID# (1-12686) 79",
  "SAMPLE ID  79 INT",
  "RACL/ETHNIC COHORT /SCRNR 79",
  "SEX OF R 79",
  "LIVE W ONE DEPRESSED MENTALLY ILL SUICIDAL <18 2012",
  "LIVE W PROBLEM DRINKER OR ALCHOLIC <18 2012",
  "LIVE W ONE DEPRESSED MENTALLY ILL SUICIDAL <18 2014",
  "LIVE W PROBLEM DRINKER OR ALCHOLIC <18 2014",
  "LIVE W ONE DEPRESSED MENTALLY ILL SUICIDAL <18 2016",
  "LIVE W PROBLEM DRINKER OR ALCHOLIC <18 2016"
)


# Use qnames rather than rnums

qnames = function(data) {
  names(data) <- c("MCASEID",
    "SAMPLEID",
    "RAC",
    "SEX",
    "HOMEDEP_2012",
    "HOMEDRINKER_2012",
    "HOMEDEP_2014",
    "HOMEDRINKER_2014",
    "HOMEDEP_2016",
    "HOMEDRINKER_2016")
  return(data)
}

df_data_home <- qnames(vallabels(new_data))

df_data_raw=merge(df_data_good,df_data_home)

```

# Summary / data cleaning
```{r}
summary(df_data_raw)


#Creat Subject Tag
df_full_gen1 = df_data_raw %>%
  mutate(SubjectTag=MCASEID*100,
        CASEID=MCASEID*100,
        HOMEDRINKER=pmax(HOMEDRINKER_2016,HOMEDRINKER_2014,HOMEDRINKER_2012, na.rm = TRUE),
       HOMEDEP=pmax(HOMEDEP_2016,HOMEDEP_2014,HOMEDEP_2012, na.rm = TRUE)
         )


#Change Reference Group for Race (to non-black-non-hispanic)
df_full_gen1 $RACE = relevel(df_full_gen1$RACE, ref=3)

```

```{r linear_regression_basics}
# name = lm([target_variable] ~ [predictor_var1 + predictor_var2 + ...], data = [data_source])
#to add linear regression line to plot use abline()

days_per_month_83 = lm(NUM_DAY_DRANK_LAST_MONTH_83 ~ as.factor(mil_groups), data = df_rni_groupings)
summary(days_per_month_83)
```
```{r race_reference_group}
df_rni_groupings$RACE=relevel(df_rni_groupings$RACE, ref='NON-BLACK, NON-HISPANIC')

```

```{r lm_num_day_controls_83}
days_per_month_83_controls = lm(NUM_DAY_DRANK_LAST_MONTH_83 ~ as.factor(mil_groups) + SAMPLE_SEX_79 + RACE, data = df_rni_groupings)
summary(days_per_month_83_controls)
```
```{r lm_age_start_82}
age_start_82 = lm(AGE_START_DRINK_82 ~ as.factor(mil_groups) + SAMPLE_SEX_79 + RACE, data = df_rni_groupings)
summary(age_start_82)
```

```{r lm_age_start_83}
age_start_83 = lm(AGE_START_DRINK_83 ~ as.factor(mil_groups) + SAMPLE_SEX_79 + RACE, data = df_rni_groupings)
summary(age_start_83)
```

```{r recode_freq6}
#COME BACK LATER TO FIX ORDINAL
df_rni_groupings <- df_rni_groupings %>% 
  mutate(recode_alc_freq6drinks_82 = case_when(ALC_FREQ6DRINKS_82 == "NEVER" ~ 0,
                                ALC_FREQ6DRINKS_82 == "ONCE" ~ 1,
                                ALC_FREQ6DRINKS_82 == "2 OR 3 TIMES" ~ 2,
                                ALC_FREQ6DRINKS_82 == "4 OR 5 TIMES" ~ 3,
                                ALC_FREQ6DRINKS_82 == "10 OR MORE TIMES" ~ 4))

df_rni_groupings <- df_rni_groupings %>% 
  mutate(recode_alc_freq6drinks_83 = case_when(ALC_FREQ6DRINK_83 == "NEVER" ~ 0,
                                ALC_FREQ6DRINK_83 == "ONCE" ~ 1,
                                ALC_FREQ6DRINK_83 == "2 OR 3 TIMES" ~ 2,
                                ALC_FREQ6DRINK_83 == "4 OR 5 TIMES" ~ 3,
                                ALC_FREQ6DRINK_83 == "10 OR MORE TIMES" ~ 4))

df_rni_groupings <- df_rni_groupings %>% 
  mutate(recode_alc_freq6drinks_84 = case_when(ALC_FREQ6DRINK_84 == "NEVER" ~ 0,
                                ALC_FREQ6DRINK_84 == "ONCE" ~ 1,
                                ALC_FREQ6DRINK_84 == "2 OR 3 TIMES" ~ 2,
                                ALC_FREQ6DRINK_84 == "4 OR 5 TIMES" ~ 3,
                                ALC_FREQ6DRINK_84 == "10 OR MORE TIMES" ~ 4))

```

```{r lm_freq_6_drinks_82}
freq_6_82 = lm(recode_alc_freq6drinks_82 ~ as.factor(mil_groups) + SAMPLE_SEX_79 + RACE, data = df_rni_groupings)
summary(freq_6_82)
```

```{r lm_freq_6_drinks_83}
freq_6_83 = lm(recode_alc_freq6drinks_83 ~ as.factor(mil_groups) + SAMPLE_SEX_79 + RACE, data = df_rni_groupings)
summary(freq_6_83)
```

```{r lm_freq_6_drinks_84}
freq_6_84 = lm(recode_alc_freq6drinks_84 ~ as.factor(mil_groups) + SAMPLE_SEX_79 + RACE, data = df_rni_groupings)
summary(freq_6_84)
```

```{r recode_impact_job}
df_rni_groupings <- df_rni_groupings %>% 
  mutate(recode_alc_impact_job_82 = case_when(ALC_IMPACT_JOB_82 == "NO" ~ 0,
                                ALC_IMPACT_JOB_82 == "YES" ~ 1))
df_rni_groupings <- df_rni_groupings %>% 
  mutate(recode_alc_impact_job_83 = case_when(ALC_IMPACT_JOB_83 == "NO" ~ 0,
                                ALC_IMPACT_JOB_83 == "YES" ~ 1))
df_rni_groupings <- df_rni_groupings %>% 
  mutate(recode_impact_job_noalc_last30_84 = case_when(ALC_IMPACT_JOB_NOALC_LAST30_84 == "NO" ~ 0,
                                ALC_IMPACT_JOB_NOALC_LAST30_84 == "YES" ~ 1))

```

```{r lm_impact_job_82} 

impact_job_82 = glm(recode_alc_impact_job_82 ~ as.factor(mil_groups) + SAMPLE_SEX_79 + RACE, data = df_rni_groupings, family = "binomial")
summary(impact_job_82)
```
```{r lm_impact_job_8} 

impact_job_83 = glm(recode_alc_impact_job_83 ~ as.factor(mil_groups) + SAMPLE_SEX_79 + RACE, data = df_rni_groupings, family = "binomial")
summary(impact_job_83)
```

```{r lm_impact_job_noalc_last30_84}
impact_job_noalc_last30_84 = glm(recode_impact_job_noalc_last30_84 ~ as.factor(mil_groups) + SAMPLE_SEX_79 + RACE, data = df_rni_groupings, family = "binomial")
summary(impact_job_noalc_last30_84)
```
```{r recode_afraid_alcoholic}
df_rni_groupings <- df_rni_groupings %>% 
  mutate(recode_afraid_alcoholic_84 = case_when(AFRAID_ALCOHOLIC_84 == "NO" ~ 0,
                                AFRAID_ALCOHOLIC_84 == "YES" ~ 1))
```

```{r lm_afraid_alcoholic_84}
afraid_alc_84 = glm(recode_afraid_alcoholic_84 ~ as.factor(mil_groups) + SAMPLE_SEX_79 + RACE, data = df_rni_groupings, family = "binomial")
summary(afraid_alc_84)
```
```{r recode_drink_til_drunk}
df_rni_groupings <- df_rni_groupings %>% 
  mutate(recode_drink_til_drunk_84 = case_when(DRINK_UNTIL_DRUNK_84 == "NO" ~ 0,
                                DRINK_UNTIL_DRUNK_84 == "YES" ~ 1))
```

```{r lm_drink_til_drunk_84}
drink_til_drunk_84 = glm(recode_drink_til_drunk_84 ~ as.factor(mil_groups) + SAMPLE_SEX_79 + RACE, data = df_rni_groupings, family = "binomial")
summary(drink_til_drunk_84)
```
```{r recode_forget_next}
df_rni_groupings <- df_rni_groupings %>% 
  mutate(recode_forget_next_84 = case_when(FORGETS_NEXT_DAY_84 == "NO" ~ 0,
                                FORGETS_NEXT_DAY_84 == "YES" ~ 1))
```

```{r lm_forget_next_84}
forget_next_84 = glm(recode_forget_next_84 ~ as.factor(mil_groups) + SAMPLE_SEX_79 + RACE, data = df_rni_groupings, family = "binomial")
summary(forget_next_84)
```
```{r recode_AM_drink}
df_rni_groupings <- df_rni_groupings %>% 
  mutate(recode_AM_drink_84 = case_when(DRINK_FIRST_MORNING_84 == "NO" ~ 0,
                                DRINK_FIRST_MORNING_84 == "YES" ~ 1))
```

```{r lm_AM_drink_first_84}
AM_drink_first_84 = glm(recode_AM_drink_84 ~ as.factor(mil_groups) + SAMPLE_SEX_79 + RACE, data = df_rni_groupings, family = "binomial")
summary(AM_drink_first_84)
```